apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: manual  # Corrected typo: "storageClasseName" -> "storageClassName"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
